version: '3'

services:
  nginx:
    image: nginx:1.17
    ports:
      - 8120:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fpm
  fpm:
    build: 
      context: .
      dockerfile: docker/fpm/Fpm.Dockerfile
    volumes:
      - ./app:/var/www/app
      - ./bootstrap:/var/www/bootstrap
      - ./config:/var/www/config
      - ./database:/var/www/database
      - ./public:/var/www/public
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
      - ./storage:/var/www/storage
      - ./tests:/var/www/tests
      - ./.env:/var/www/.env
      - ./artisan:/var/www/artisan
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./phpunit.xml:/var/www/phpunit.xml
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - web6-percona
  web6-percona:
    image: percona:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - percona-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  redis:
    image: redis:4
volumes:
  percona-data: # БД
